### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by vselivanyuk** [waslost0/RollercoinBot#1]
Hello
I installed requirements successfully

```
PS C:\Users\human\Source\Repos\RollercoinBot> py -m pip install -r requirements.txt
Requirement already satisfied: opencv-python==4.4.0.44 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (4.4.0.44)
Requirement already satisfied: keyboard~=0.13.5 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.13.5)
Requirement already satisfied: Pillow~=8.0.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (8.0.1)
Requirement already satisfied: numpy==1.19.2 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 4)) (1.19.2)
Requirement already satisfied: Multi-Template-Matching~=1.6.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: PyAutoGui==0.9.52 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 6)) (0.9.52)
Requirement already satisfied: pandas in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.1.5)
Requirement already satisfied: opencv-python-headless in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (4.5.2.54)
Requirement already satisfied: scipy in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.7.0)
Requirement already satisfied: scikit-image in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (0.18.2)
Requirement already satisfied: pymsgbox in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (1.0.3)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.1.27)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.0.9)
Requirement already satisfied: mouseinfo in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from pandas->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from pandas->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.8.1)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2021.6.14)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (3.4.2)
Requirement already satisfied: networkx>=2.0 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.5.1)
Requirement already satisfied: imageio>=2.3.0 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.9.0)
Requirement already satisfied: pyrect in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from pygetwindow>=0.0.5->PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.1.4)
Requirement already satisfied: pyperclip in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from mouseinfo->PyAutoGui==0.9.52->-r requirements.txt (line 6)) (1.8.2)
Requirement already satisfied: six>=1.5 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from python-dateutil>=2.7.3->pandas->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.16.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirementRequirement already satisfied: cycler>=0.10 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (0.10.0)
Requirement already satisfied: decorator<5,>=4.3 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from networkx>=2.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (4.4.2)

```

After starting the bot, it gives an error:

```
PS C:\Users\human\Source\Repos\RollercoinBot> py bot.py

Statistics:
 Time running: 0:00:00.256314
 Played Games:  0

Traceback (most recent call last):
  File "bot.py", line 446, in <module>
    main()
  File "bot.py", line 435, in main
    if bot().can_start():
  File "bot.py", line 206, in can_start
    return check_image(self.start_img_path)
  File "bot.py", line 96, in check_image
    b, _ = find_image(img, screen_grab())
  File "bot.py", line 81, in find_image
    searchBox=None)
  File "C:\Users\human\AppData\Local\Programs\Python\Python37\lib\site-packages\MTM\__init__.py", line 227, in matchTemplates
    tableHit = findMatches(listTemplates, image, method, N_object, score_threshold, searchBox)
  File "C:\Users\human\AppData\Local\Programs\Python\Python37\lib\site-packages\MTM\__init__.py", line 143, in findMatches
    corrMap = computeScoreMap(template, image, method, mask=mask)
  File "C:\Users\human\AppData\Local\Programs\Python\Python37\lib\site-packages\MTM\__init__.py", line 58, in computeScoreMap
    if template.dtype == "float64" or image.dtype == "float64":
AttributeError: 'NoneType' object has no attribute 'dtype'

```

**Comment by krekel1** [comment]
same

**Comment by waslost0** [comment]
> same



> Hello
> I installed requirements successfully
> 
> ```
> PS C:\Users\human\Source\Repos\RollercoinBot> py -m pip install -r requirements.txt
> Requirement already satisfied: opencv-python==4.4.0.44 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 1)) (4.4.0.44)
> Requirement already satisfied: keyboard~=0.13.5 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 2)) (0.13.5)
> Requirement already satisfied: Pillow~=8.0.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 3)) (8.0.1)
> Requirement already satisfied: numpy==1.19.2 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 4)) (1.19.2)
> Requirement already satisfied: Multi-Template-Matching~=1.6.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 5)) (1.6.1)
> Requirement already satisfied: PyAutoGui==0.9.52 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from -r requirements.txt (line 6)) (0.9.52)
> Requirement already satisfied: pandas in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.1.5)
> Requirement already satisfied: opencv-python-headless in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (4.5.2.54)
> Requirement already satisfied: scipy in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.7.0)
> Requirement already satisfied: scikit-image in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (0.18.2)
> Requirement already satisfied: pymsgbox in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (1.0.9)
> Requirement already satisfied: PyTweening>=1.0.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (1.0.3)
> Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.1.27)
> Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.0.9)
> Requirement already satisfied: mouseinfo in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.1.3)
> Requirement already satisfied: pytz>=2017.2 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from pandas->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2021.1)
> Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from pandas->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.8.1)
> Requirement already satisfied: tifffile>=2019.7.26 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2021.6.14)
> Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.1.1)
> Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (3.4.2)
> Requirement already satisfied: networkx>=2.0 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.5.1)
> Requirement already satisfied: imageio>=2.3.0 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.9.0)
> Requirement already satisfied: pyrect in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from pygetwindow>=0.0.5->PyAutoGui==0.9.52->-r requirements.txt (line 6)) (0.1.4)
> Requirement already satisfied: pyperclip in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from mouseinfo->PyAutoGui==0.9.52->-r requirements.txt (line 6)) (1.8.2)
> Requirement already satisfied: six>=1.5 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from python-dateutil>=2.7.3->pandas->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (1.16.0)
> Requirement already satisfied: pyparsing>=2.2.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (2.4.7)
> Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirementRequirement already satisfied: cycler>=0.10 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (0.10.0)
> Requirement already satisfied: decorator<5,>=4.3 in c:\users\human\appdata\local\programs\python\python37\lib\site-packages (from networkx>=2.0->scikit-image->Multi-Template-Matching~=1.6.1->-r requirements.txt (line 5)) (4.4.2)
> ```
> 
> After starting the bot, it gives an error:
> 
> ```
> PS C:\Users\human\Source\Repos\RollercoinBot> py bot.py
> 
> Statistics:
>  Time running: 0:00:00.256314
>  Played Games:  0
> 
> Traceback (most recent call last):
>   File "bot.py", line 446, in <module>
>     main()
>   File "bot.py", line 435, in main
>     if bot().can_start():
>   File "bot.py", line 206, in can_start
>     return check_image(self.start_img_path)
>   File "bot.py", line 96, in check_image
>     b, _ = find_image(img, screen_grab())
>   File "bot.py", line 81, in find_image
>     searchBox=None)
>   File "C:\Users\human\AppData\Local\Programs\Python\Python37\lib\site-packages\MTM\__init__.py", line 227, in matchTemplates
>     tableHit = findMatches(listTemplates, image, method, N_object, score_threshold, searchBox)
>   File "C:\Users\human\AppData\Local\Programs\Python\Python37\lib\site-packages\MTM\__init__.py", line 143, in findMatches
>     corrMap = computeScoreMap(template, image, method, mask=mask)
>   File "C:\Users\human\AppData\Local\Programs\Python\Python37\lib\site-packages\MTM\__init__.py", line 58, in computeScoreMap
>     if template.dtype == "float64" or image.dtype == "float64":
> AttributeError: 'NoneType' object has no attribute 'dtype'
> ```



Screen resolution must be 1920 * 1080

**Comment by krekel1** [comment]
ok thanks i was running it on virtual machine but now i changed it thanks!!! can i also do it at 1600 x 900

**Comment by vselivanyuk** [comment]
> Разрешение экрана должно быть 1920 * 1080

![image](https://user-images.githubusercontent.com/86662856/123848914-acc2bb00-d931-11eb-8518-f8eba1768027.png)
I already have this

**Comment by krekel1** [comment]
it does not work ):

**Comment by krekel1** [comment]
do you need Microsoft Visual Studio? i dont have it. can that be the reason that it does not work?

**Comment by krekel1** [comment]
the problem is you dont have Microsoft Visual Studio

**Comment by vselivanyuk** [comment]
> the problem is you dont have Microsoft Visual Studio

I tried running in Microsoft Visual Studio and Visual Studio Code

**Comment by krekel1** [comment]
Dont run it but install it (select nodejs and python) and run it in
powershell / cmd

Op wo 30 jun. 2021 20:24 schreef vselivanyuk ***@***.***>:

**Comment by outsdec** [comment]
File "bot.py", line 14, in <module>
    from MTM import matchTemplates
ModuleNotFoundError: No module named 'MTM'
